### ISSUE TITLE
Code for multiple-server

### ISSUE THREAD

**Issue by Expelliarmus-rg** [snsong/soCoM#2]
Hi, I could not find code related to the  multiple-server scenario. Did I miss something?

**Comment by snsong** [comment]
Thank you for informing us. We have update the soCoM with multiple servers scenario and mobile user control. This part is related to other ongoing researches, and there is no more description for the mobile models in the reference paper.

**Comment by Expelliarmus-rg** [comment]
Thank you!

**Comment by Expelliarmus-rg** [comment]
Hi, do you have some recommended paper for channel interference related to the multiple-server-multiple-user scenario?
I am confused with that part in code soCoMM. How do you calculate the bandwidth allocation? And what does 'CD' mean?

**Comment by snsong** [comment]
Hi, I am sorry that there is no referece paper for the bandwith allocation in source code. In fact, you can use any bandwidth allocation method.Our method just wants to simulate a dynamic allocation situation. In our method, each time the user can get 1/cd of the remaining bandwidth. Compared with the average or fixed bandwidth allocation strategy, our method complicates the situation and is used to verify the robustness of the deep learning method. The bandwidth allocation strategy we give meets the following characteristics: it cannot be preempted, and the bandwidth obtained decreases with the increase of transmission tasks. The simulation is based on high-level abstraction, ignoring the value of specific parameters such as channel gain, space noise, and so on.
Because our research focus is not on bandwidth allocation strategies, perhaps this approach is not very sensible. Maybe you can try to add noise or choose other bandwidth allocation methods to examine the effect of the deep model. If you want to achieve a more specific simulation, you can refer to:
[1] X. Chen, L. Jiao, W. Li, and X. Fu, “Efficient multi-user computation offloading for mobile-edge cloud computing,” IEEE/ACM Transactions on Networking, vol. 24, no. 5, pp. 2795–2808, 2015.

Best wishes

**Comment by Expelliarmus-rg** [comment]
Got it! Thank you~
